# Generated by Django 2.2 on 2021-05-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('books_app', '0003_remove_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='liked_reviews', to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
