# Generated by Django 2.2 on 2021-04-21 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_one.Course')),
            ],
        ),
    ]
