# Generated by Django 2.2 on 2021-04-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
